"""Generate a standalone curl-downloadable runner from reviewed local sources."""
import argparse
import base64
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FILES = ('scripts/theme.py', 'docs/upstream-lock.json',
         'dist/kitty-christmas.css', 'dist/kitty-easter.css', 'dist/kitty-beach-summer.css', 'dist/kitty-halloween-fall.css')
BOOTSTRAP = r'''
import argparse, base64, hashlib, json, sys, tempfile
from pathlib import Path

if sys.version_info < (3, 9):
    sys.exit('Python 3.9+ is required.')
p = argparse.ArgumentParser(prog='meow-kitteh-runner', description="Meow Kitteh — experimental Pi-hole Web v6.6 theme runner. Default: dry-run; no FTL changes.")
p.add_argument('action', choices=('install','upgrade','update','uninstall','rollback','recover'))
p.add_argument('--theme', choices=('kitty-christmas', 'kitty-easter', 'kitty-beach-summer', 'kitty-halloween-fall'))
p.add_argument('--web-root', default='/var/www/html/admin')
p.add_argument('--state-dir', default='/var/lib/pi-hole-meow-kitteh')
mode = p.add_mutually_exclusive_group()
mode.add_argument('--apply', action='store_true', help='Write changes after reviewing a dry-run')
mode.add_argument('--dry-run', action='store_true', help='Explicit read-only target check (the default)')
p.add_argument('--version', action='version', version=VERSION + ' / payload ' + DIGEST[:12])
if len(sys.argv) == 1 or sys.argv[1:] == ['help']:
    p.print_help(); sys.exit(0)
a = p.parse_args()
raw = base64.b64decode(PAYLOAD, validate=True)
if hashlib.sha256(raw).hexdigest() != DIGEST:
    p.exit(1, 'Refused: runner payload checksum mismatch\n')
files = json.loads(raw)
if set(files) != set(EXPECTED):
    p.exit(1, 'Refused: unexpected payload file set\n')
print('Meow Kitteh ' + VERSION + ' / payload ' + DIGEST[:12], flush=True)
print('Mode: ' + ('APPLY' if a.apply else 'DRY RUN — target and restore journal will not be changed'), flush=True)
print('Target: ' + a.web_root + '\nRestore journal: ' + a.state_dir, flush=True)
# Build an ephemeral package, not a checkout; never download or execute more code.
with tempfile.TemporaryDirectory(prefix='meow-kitteh-runner-') as tmp:
    root = Path(tmp)
    for name, encoded in files.items():
        target = root / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(base64.b64decode(encoded, validate=True))
    sys.path.insert(0, str(root / 'scripts'))
    import theme
    selected = a.theme
    action = 'update' if a.action == 'upgrade' else a.action
    try:
        if action == 'install' and selected is None:
            selected = 'kitty-christmas'
        if action == 'update' and selected is None:
            # Older journals predate the runner. Infer only a known palette marker.
            journal = Path(a.state_dir) / 'state.json'
            theme.regular(journal)
            state = json.loads(journal.read_text())
            current = theme.unpack(state['history'][-1]).decode('utf-8')
            choices = [name for name in theme.THEMES if '/* Original palette: ' + name + '.' in current]
            if len(choices) != 1:
                raise ValueError('Cannot identify installed theme; specify --theme explicitly')
            selected = choices[0]
        if selected: print('Theme: ' + selected, flush=True)
        result = theme.run(action, a.web_root, a.state_dir, selected, a.apply)
        print(result)
        if action in ('install','update'):
            print('Activation: select the existing LCARS theme in Pi-hole settings, then hard-refresh. FTL configuration was not changed.')
        elif action in ('uninstall','rollback'):
            print('Restore your previous Pi-hole theme setting manually if needed; FTL configuration was not changed.')
    except (ValueError, OSError, KeyError, IndexError, UnicodeError) as exc:
        p.exit(1, 'Refused: ' + str(exc) + '\n')
'''

def render():
    files = {name: base64.b64encode((ROOT/name).read_bytes()).decode() for name in FILES}
    raw = json.dumps(files, sort_keys=True, separators=(',', ':')).encode()
    metadata = ('VERSION = ' + repr((ROOT/'VERSION').read_text().strip()) + '\n' +
                'DIGEST = ' + repr(hashlib.sha256(raw).hexdigest()) + '\n' +
                'EXPECTED = ' + repr(FILES) + '\n' +
                'PAYLOAD = ' + repr(base64.b64encode(raw).decode()) + '\n')
    license_header = ''.join('# ' + line + '\n' for line in ((ROOT/'LICENSE').read_text() + '\n' + (ROOT/'ARTWORK-NOTICE.md').read_text()).splitlines())
    return '#!/bin/sh\n' + license_header + '''# Generated by scripts/build_runner.py. Original code: MIT; see repository LICENSE.
# Download and inspect this file before running. Requires Python 3.9+; never invokes sudo.
# No action defaults to help. Mutations require --apply. Payload checksum is not a signature.
set -eu
main() {
  command -v python3 >/dev/null 2>&1 || { echo 'Python 3.9+ is required.' >&2; return 1; }
  python3 - "$@" <<'GALACTIC_PYTHON'
''' + metadata + BOOTSTRAP + '''
GALACTIC_PYTHON
}
main "$@"
'''

if __name__ == '__main__':
    p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
    target=ROOT/'run.sh';result=render()
    if a.check:
        if not target.exists() or target.read_text()!=result: p.exit(1,'run.sh is stale; run scripts/build_runner.py\n')
    else:
        target.write_text(result);target.chmod(0o755)
